export enum Routes {
  CAREER = "/services",
  CONTACT = "/contact",
  HOME = "/home",
  About = "/about-us",
  LAYOUT = "/layout",
  PARTNER_WITH_US = "/partner-with-us",
  PRICING = "/coverage",
  PRODUCTS_CALL_CENTER = "/products/call-center",
  PRODUCTS_CONTRACTS = "/products/contracts",
  PRODUCTS_LOYALTY = "/products/loyalty",
  PRODUCTS_MARKETING = "/products/marketing",
  PRODUCTS_OPERATION = "/products/operation",
  PRODUCTS = "/products",
  PRODUCTS_PAGES = "/products/pages",
  PRODUCTS_SALES = "/products/sales",
  AGENTIC_007 = '/agentic-007',
  PRODUCTS_SERVICES = "/products/services",
  PRODUCTS_MEETINGS = "/products/meetings",
  PRIVACY_POLICY = "/privacy-policy",
  TERMS_OF_SERVICE = "Terms-of-Service",
}
